var prefs=new gadgets.Prefs,initialHeight="settings"in window?window.innerHeight||document.documentElement.clientHeight||document.getElementsByTagName("body")[0].clientHeight:gadgets.util.getBodyElement().clientHeight,visualizationType=prefs.getString("visualizationType");""==visualizationType&&(visualizationType="Table");"Maps"==visualizationType&&(visualizationType="MarkerClusterer");var useMapView=!1,prefDisplayOrder=unescape(prefs.getString("displayOrder")),displayOrder=[];
if(Array.isArray(prefDisplayOrder))displayOrder=prefDisplayOrder;else try{displayOrder=JSON.parse(prefDisplayOrder)}catch(e$$7){prefDisplayOrder=""}if(""==prefDisplayOrder||0==displayOrder.length)displayOrder=["map","filters","chart"];if("MapsWithTable"==visualizationType)visualizationType="Table",useMapView=!0;else for(var i=0;i<displayOrder.length;i++)if("map"==displayOrder[i]){displayOrder.splice(i,1);displayOrder.push("");break}
var wrapper,data,dataTemplate,csvFilters=[],columnsToDisplay=[],sidebarColumn="",columnsLayout=1,subTables=[],idColumn="",idColumnPosition=void 0,queryString="",queryStringTemplate="",noProxy=!1,q=void 0,startPage=0,selectedRow=[],view=null,bi_charts=[],loader,filterList=[],filterList_c=0,dependentFilterList=[],sidebar=void 0,filterQuery="",filterSettings={},ISAppsScriptProxyUsed="",mapsParam={ISmapsLoaded:!1,MustReload:!1,ISinsideUpdate:!1,markers:[],column:{},divID:"middleContainer",geocoder:{run:!1,
index:0,markers:[],bounds:void 0,timeOut:250}},useRowsToDisplay=!1,rowsToDisplay=[],doNotShowMarker=!1,customCSS=prefs.getString("customCSS");-1!=customCSS.indexOf("http")&&(document.getElementById("awesomeTableCSS").href=customCSS);
(function(a,f,e,b,c,g,d){a.GoogleAnalyticsObject=c;a[c]=a[c]||function(){(a[c].q=a[c].q||[]).push(arguments)};a[c].l=1*new Date;g=f.createElement(e);d=f.getElementsByTagName(e)[0];g.async=1;g.src=b;d.parentNode.insertBefore(g,d)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");ga("create","UA-17877121-2","auto",{name:"gadgetTracking"});ga("create","UA-17877121-5","auto",{name:"awesomeTableTracking"});
""!=prefs.getString("codeAnalytics")&&void 0!=prefs.getString("codeAnalytics")&&ga("create",prefs.getString("codeAnalytics"),"auto");var idDIV=["topContainer","middleContainer","bottomContainer"],structDIV=[];structDIV.push(document.getElementById(idDIV[0]));structDIV.push(document.getElementById(idDIV[1]));structDIV.push(document.getElementById(idDIV[2]));var chartHTML=structDIV[2].innerHTML;structDIV[2].innerHTML="";
for(i=0;i<displayOrder.length;i++){if("filters"==displayOrder[i]){var tmpDIV=document.createElement("div");tmpDIV.id="controlersPanel";structDIV[i].appendChild(tmpDIV);delete tmpDIV}else"chart"==displayOrder[i]?("MarkerClusterer"==visualizationType?mapsParam.divID=idDIV[i]:structDIV[i].innerHTML=chartHTML,delete chartHTML):"map"==displayOrder[i]&&(mapsParam.divID=idDIV[i]);""!=displayOrder[i]?structDIV[i].style.display="":structDIV[i].innerHTML=""}
if("MarkerClusterer"==visualizationType||1==useMapView){var mapsGeocoding=function(a,f){try{if(f==google.maps.GeocoderStatus.OK){0==mapsParam.geocoder.index||void 0==mapsParam.geocoder.bounds?void 0!=a[0].geometry.location&&(mapsParam.geocoder.bounds=new google.maps.LatLngBounds(a[0].geometry.location,a[0].geometry.location)):mapsParam.geocoder.bounds.extend(a[0].geometry.location);if(mapsParam.geocoder.bounds.getNorthEast().equals(mapsParam.geocoder.bounds.getSouthWest())){var e=mapsParam.geocoder.bounds.getCenter();
mapsParam.geocoder.bounds.extend(new google.maps.LatLng(e.lat()+1,e.lng()+1));mapsParam.geocoder.bounds.extend(new google.maps.LatLng(e.lat()-1,e.lng()-1))}mapsParam.geocoder.markers.push(new google.maps.Marker({map:mapsParam.map,position:a[0].geometry.location,animation:google.maps.Animation.DROP}));mapsParam.map.fitBounds(mapsParam.geocoder.bounds);data.setValue(mapsParam.geocoder.index,mapsParam.column.lat,a[0].geometry.location.lat());data.setValue(mapsParam.geocoder.index,mapsParam.column.lng,
a[0].geometry.location.lng());mapsParam.geocoder.index++;mapsParam.geocoder.timeOut=500}else f==google.maps.GeocoderStatus.OVER_QUERY_LIMIT?mapsParam.geocoder.timeOut*=2:(mapsParam.geocoder.index++,mapsParam.geocoder.timeOut=500)}catch(b){mapsParam.geocoder.index++}mapsParam.geocoder.index<data.getNumberOfRows()?setTimeout(function(){mapsParam.geocoder.g.geocode({address:data.getValue(mapsParam.geocoder.index,mapsParam.column.address)},mapsGeocoding)},mapsParam.geocoder.timeOut):(mapsParam.geocoder.run=
!1,mapsParam.geocoder.markers.forEach(function(a,b){a.setMap(null)}),mapsParam.geocoder.markers=[],setTimeout(refresh,50))},MarkerClustererInitialize=function(){mapsParam.ISmapsLoaded=!0;1==mapsParam.MustReload&&(mapsParam.MustReload=!1,mapsMarkerClustererFirstLoad(),setTimeout(function(){UPDATE_MAP_MARKERCLUSTERER(dataTable)},50))},mapsMarkerClustererFirstLoad=function(){mapsParam.map=new google.maps.Map(document.getElementById(mapsParam.divID),{center:{lat:42.25192,lng:8.3800983},zoom:3});mapsParam.mc=
new MarkerClusterer(mapsParam.map,{},{zoomOnClick:!1,averageCenter:!0,gridSize:40});mapsParam.InfoWindow=new google.maps.InfoWindow({content:""});google.maps.event.addListener(mapsParam.mc,"clusterclick",function(a){var f=a.getBounds();if(f.getNorthEast().equals(f.getSouthWest())){for(var f=a.getMarkers(),e=[],b=0;b<f.length;b++)e.push(f[b].toolTip);openInfoWindow(e,a.getCenter(),0)}else mapsParam.map.fitBounds(f)});mapsParam.geocoder.g=new google.maps.Geocoder;1==mapsParam.geocoder.run&&(mapsParam.geocoder.index=
0,mapsParam.geocoder.g.geocode({address:data.getValue(0,mapsParam.column.address)},mapsGeocoding))},openInfoWindow=function(a,f,e){0>e&&(e=a.length-1);e>=a.length&&(e=0);mapsParam.InfoWindow.index=e;mapsParam.InfoWindow.markerToolTips=a;mapsParam.InfoWindow.clusterPosition=f;var b='<div style="text-align: center;"><img style="padding-right: 10px; padding-left: 10px; cursor: pointer;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAMCAYAAABfnvydAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVQY042QSQ4AIAgDp3684eV4Mx4U6K2ZpizwkO20nQB6wdurghEhVfA0/CCAKgiwaNSPGC05OvMXonv1Bj5iKvQE8361AAAAAElFTkSuQmCC" onclick="openInfoWindow(mapsParam.InfoWindow.markerToolTips, mapsParam.InfoWindow.clusterPosition, mapsParam.InfoWindow.index - 1)"><div style="display: inline-block;">'+
(e+1).toString()+"/"+a.length+'</div><img style="padding-right: 10px; padding-left: 10px; cursor: pointer;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAMCAYAAABfnvydAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAQklEQVQY042Q0QoAIAgDz358+OX1VKBYtifBY84BIGlKmhSyvHB3C8B2uEFnuEHBroIsh8rQoNH/iWfI55tdUXRVLxYOLHghvYMKAAAAAElFTkSuQmCC" onclick="openInfoWindow(mapsParam.InfoWindow.markerToolTips, mapsParam.InfoWindow.clusterPosition, mapsParam.InfoWindow.index + 1)"></div>',b=b+a[e];null!=mapsParam.InfoWindow.getMap()&&
mapsParam.InfoWindow.close();mapsParam.InfoWindow.setContent(b);mapsParam.InfoWindow.setPosition(f);mapsParam.InfoWindow.open(mapsParam.map)};(function(){var a=document.createElement("script");a.type="text/javascript";a.src="//maps.googleapis.com/maps/api/js?key=AIzaSyA4ja0ioQAXG_cx8RDNi7INzxY3YRrYbCc&v=3.exp&callback=MarkerClustererInitialize";document.body.appendChild(a)})();(function(){var a=document.createElement("script");a.type="text/javascript";a.src="//sites.google.com/site/scriptsexamples/markerclusterer_compiled.js";
document.body.appendChild(a)})()}
function getData(){t=10;loader=setInterval(function(){document.getElementById("loader").style.width=t+"%";t+=(100-t)/10;96<t&&clearInterval(loader)},1E3);var a=prefs.getString("url"),f=/https?:\/\/[^\/]*?\/(?:a\/([^\/]+?)\/)?spreadsheets\/d\/([^\/]+?)\/|https?:\/\/[^\/]+?\/(?:a\/([^\/]+?)\/)?spreadsheet\/ccc\?[^\/]*?key=([^\/]+?)(?=#|$|&)/.exec(a),e="",b="",c=!0;if(null==f){if(0==/^[^\/]+$/.test(a)){document.body.style.backgroundColor=prefs.getString("backgroundColor");document.getElementById("loader").style.display=
"none";document.getElementById("dashboard").style.display="inline";document.getElementById("dashboard").innerHTML='<div style="text-align:center; width:100%">You have not selected a Google Sheet URL. Make sure you click on the green Save button to save your gadget parameters.<img src="http://goo.gl/iyV9mc"></div>';return}f=/sites\.google\.com\/a\/([^\/]+?)\//.exec(document.referrer);null!=f&&(e="a/"+f[1]+"/");b=a}else void 0!=f[2]?(void 0!=f[1]&&(e="a/"+f[1]+"/"),b=f[2],c=!1):(void 0!=f[3]&&(e="a/"+
f[3]+"/"),b=f[4]);urlFormatted=0==c?"https://docs.google.com/"+e+"spreadsheets/d/"+b+"/gviz/tq?":"https://docs.google.com/"+e+"spreadsheet/ccc?key="+b+"&";queryString=urlFormatted+"headers=2&range="+prefs.getString("range")+"&sheet="+prefs.getString("sheet");if(prefs.getString("rangeTemplate")){var g=prefs.getString("rangeTemplate").split("!");queryStringTemplate=urlFormatted+"headers=0&range="+g[1]+"&sheet="+g[0]}a=document.referrer.match(/(?:\?|&)q=(.+?)(?:$|&)/);null!=a&&(q=decodeURIComponent(a[1]));
a=document.referrer.match(/(?:\?|&)(?:c|C)=(\w+)(?:$|&)/);null!=a&&(idColumn=a[1]);for(a=/(?:\?|&)filter([a-z]+)=([\w%\-\_\.\!\~\*\'\(\),]+)(?=$|&)/ig;null!==(f=a.exec(document.referrer));)if(e=f[1],f=f[2].split(","),0<f.length){b=[];for(c=0;c<f.length;c++)b.push(decodeURIComponent(f[c]));filterSettings[e]=b}a=prefs.getString("queryOpt");""!=a&&(a=unescape(a.replace(/&#39;/g,"'").replace(/&#34;/g,"'").replace(/&#60;/g,"<").replace(/&#62;/g,">")),-1!=a.indexOf("sidebar ")&&(sidebarColumn=a.split("sidebar ")[1].split(" ")[0],
idColumn=a.split("elect ")[1].split(",")[0]),-1!=a.indexOf("columnsLayout ")&&(columnsLayout=a.split("columnsLayout ")[1].split(" ")[0]),a=a.replace(" sidebar "+sidebarColumn,"").replace(" columnsLayout "+columnsLayout,""));""!=prefs.getString("scriptProxy")&&void 0!=prefs.getString("scriptProxy")&&0==noProxy?(script=document.createElement("script"),script.type="text/javascript",a=prefs.getString("scriptProxy")+"?url="+queryString,void 0!=document.referrer.split("?")[1]&&(f="&"+document.referrer.split("?")[1],
a+=f.replace("&c=","&C=")),a+="&callback=handleProxyResponse",void 0!=g&&(a+="&templateSheet="+g[0]+"&templateRange="+g[1]),script.src=a,g=document.getElementsByTagName("script")[0],g.parentNode.insertBefore(script,g),ISAppsScriptProxyUsed=" with Proxy"):(g=new google.visualization.Query(queryString),""!=a&&-1==a.indexOf("#")&&g.setQuery(a),g.send(handleQueryResponse))}
function handleProxyResponse(a){document.getElementById("dashboard").style.display="inline";if(a.noProxy)return noProxy=!0,getData();data=new google.visualization.DataTable(a.dataTable);processLabelsInData();"template"in a?handleQueryResponseForTemplate({},new google.visualization.DataTable(a.template)):drawVisualization(data)}
function handleQueryResponse(a){document.getElementById("dashboard").style.display="inline";if(a.isError()){var f=decodeURI(prefs.getString("errorMSG"));""==f?document.getElementById("dashboard").innerHTML='<div style="text-align:center; width:100%">Error: '+a.getMessage()+" "+a.getDetailedMessage()+"</div>":document.getElementById("dashboard").innerHTML='<div style="text-align:center; width:100%">'+f+"</div>"}else data=a.getDataTable(),processLabelsInData(),queryStringTemplate?(new google.visualization.Query(queryStringTemplate)).send(handleQueryResponseForTemplate):
drawVisualization(data)}
function handleQueryResponseForTemplate(a,f){if("isError"in a&&a.isError()){var e=decodeURI(prefs.getString("errorMSG"));""==e?document.getElementById("dashboard").innerHTML='<div style="text-align:center; width:100%">Error: '+a.getMessage()+" "+a.getDetailedMessage()+"</div>":document.getElementById("dashboard").innerHTML='<div style="text-align:center; width:100%">'+e+"</div>"}else{dataTemplate=f||a.getDataTable();for(var b=dataTemplate.getNumberOfColumns(),c=data.getNumberOfColumns(),e=data.getNumberOfRows(),
g=[],d=0;d<b;d++)for(var l=dataTemplate.getValue(0,d),m=0;m<c;m++)if(data.getColumnLabel(m)==l){g[l]={pos:m,template:dataTemplate.getValue(1,d)};break}b={};for(templateItem in g)if("template"in g[templateItem]&&void 0!=g[templateItem].template&&(l=g[templateItem].template.match(/[$]{"[^"]+"}/g),null!=l))for(m=0;m<l.length;m++)if(!(l[m]in b)){var h=l[m].match(/[$]{"([^"]+)"}/)[1];if(null!=h)for(d=0;d<c;d++)data.getColumnLabel(d)==h&&(b[l[m]]={value:h,position:d})}for(columnTemplate in g)for(m=0;m<
e;m++)if(c=g[columnTemplate].template,void 0!=c){for(markers in b)(d=data.getFormattedValue(m,b[markers].position))||(d=""),c=c.replace(new RegExp(markers.replace(/([.*+?^=!:${}()|\[\]\/\\])/g,"\\$1"),"g"),d);data.setValue(m,g[columnTemplate].pos,c)}drawVisualization(data)}}
function processLabelsInData(){if(0>data.getNumberOfRows()-1){var a=decodeURI(prefs.getString("errorMSG"));""==a?document.getElementById("dashboard").innerHTML='<div style="text-align:center; width:100%">No data to display.</div>':document.getElementById("dashboard").innerHTML='<div style="text-align:center; width:100%">'+a+"</div>"}else{var a=/^\s+|\s+$|(?:(?:\s?-\s?|\s)(NoFilter|Sidebar|MapsLat|MapsLong|MapsTooltip|MapsAddress|DateFilter|DateRangeFilter|StringFilter|Hidden|csvFilter|(CategoryFilter)(?:\s?\(([A-Z,]+)\))?)(?:\s?-\s?(?!\w)|\s(?!\w))?)/ig,
f={nofilter:1,hidden:2,sidebar:3,mapslat:3,mapslong:3,mapstooltip:3,mapsaddress:3},e=data.getNumberOfColumns();filterList_c=0;filterList=[];dependentFilterList=[];sidebar=void 0;if(""!=sidebarColumn)for(var b=0;b<e;b++)if(data.getColumnId(b)==sidebarColumn){sidebar=b;break}if(""!=idColumn)for(b=0;b<e;b++){if(data.getColumnId(b)==idColumn){idColumnPosition=b;break}}else idColumnPosition=0;for(var c=0;c<e;c++){var g=data.getColumnId(c);columnsToDisplay.push(c);for(var d=data.getColumnLabel(c),l=[],
m,b=a;null!==(m=b.exec(d));){var h={};void 0!=m[2]?h=void 0!=m[3]?{filter:m[2].toLowerCase(),param:m[3]}:{filter:m[2].toLowerCase()}:void 0!=m[1]&&(h={filter:m[1].toLowerCase()});h.priority=0;h.filter in f&&(h.priority=f[h.filter]);l.push(h)}"number"!=data.getColumnType(c)||l.some(function(a,b,c){return"datefilter"==a.filter?!0:!1})||(h={filter:"numberrangefilter",priority:-1},l.push(h));l.sort(function(a,b){return b.priority-a.priority});data.setColumnLabel(c,data.getColumnLabel(c).replace(a,""));
d=data.getColumnLabel(c);for(b=0;b<l.length;b++)if("mapslat"==l[b].filter)mapsParam.column.lat=c;else if("mapslong"==l[b].filter)mapsParam.column.lng=c;else if("mapstooltip"==l[b].filter)mapsParam.column.tooltip=c;else if("mapsaddress"==l[b].filter)mapsParam.column.address=c;else if("sidebar"==l[b].filter)sidebar=c;else if("hidden"==l[b].filter)columnsToDisplay.pop();else if("nofilter"==l[b].filter)break;else if("stringfilter"==l[b].filter){h=document.createElement("div");h.id="controlers"+filterList_c;
h.className="controlers-filters";h.dataset.filterType=l[b].filter;document.getElementById("controlersPanel").appendChild(h);l=prefs.getString("categoryCaption");b="vertical";"insidefilter"==l.toLowerCase()&&(b="horizontal");d={controlType:"StringFilter",containerId:"controlers"+filterList_c,options:{filterColumnIndex:c,filterColumnLabel:d,useFormattedValue:!0,matchType:"any",ui:{label:d,labelStacking:b}}};g in filterSettings&&(d.state={value:filterSettings[g][0]});g=new google.visualization.ControlWrapper(d);
filterList.push([g,c]);filterList_c++;break}else if("numberrangefilter"==l[b].filter){h=document.createElement("div");h.id="controlers"+filterList_c;h.className="controlers-filters";h.dataset.filterType=l[b].filter;document.getElementById("controlersPanel").appendChild(h);d={controlType:"NumberRangeFilter",containerId:"controlers"+filterList_c,options:{filterColumnIndex:c,filterColumnLabel:d,ui:{label:d,labelStacking:"vertical",format:{pattern:"#"}}}};g in filterSettings&&(d.state={lowValue:filterSettings[g][0],
highValue:filterSettings[g][1]});g=new google.visualization.ControlWrapper(d);filterList.push([g,c]);filterList_c++;break}else if("datefilter"==l[b].filter){h=document.createElement("div");h.id="controlers"+filterList_c;h.className="controlers-filters";h.dataset.filterType=l[b].filter;document.getElementById("controlersPanel").appendChild(h);l=prefs.getString("dateFormat");d={controlType:"DateRangeFilter",containerId:"controlers"+filterList_c,options:{filterColumnIndex:c,filterColumnLabel:d,ui:{label:d,
labelStacking:"vertical",format:{pattern:l}}}};g in filterSettings&&(d.state={lowValue:filterSettings[g][0],highValue:filterSettings[g][1]});g=new google.visualization.ControlWrapper(d);filterList.push([g,c]);filterList_c++;break}else if("daterangefilter"==l[b].filter){m=document.createElement("div");m.className="controlers-filters";var p=document.createElement("div");p.dataset.filterIndex=c;p.innerHTML='<input data-range-extent="low" type="date"><div style="padding-top:5px"></div><input data-range-extent="high" type="date">';
h=document.createElement("div");h.id="controlers"+filterList_c;h.dataset.filterType=l[b].filter;h.style.display="none";m.appendChild(p).appendChild(h);document.getElementById("controlersPanel").appendChild(m);d={controlType:"DateRangeFilter",containerId:"controlers"+filterList_c,options:{filterColumnIndex:c,filterColumnLabel:d,ui:{label:d}}};g in filterSettings&&(d.state={lowValue:filterSettings[g][0],highValue:filterSettings[g][1]});g=new google.visualization.ControlWrapper(d);filterList.push([g,
c]);filterList_c++;break}else if("categoryfilter"==l[b].filter||"csvfilter"==l[b].filter){m=null;if("param"in l[b])for(var h=l[b].param.split(","),n=0;n<e;n++)for(p=0;p<h.length;p++)data.getColumnId(n)==h[p]&&dependentFilterList.push([c,n]);h=document.createElement("div");h.id="controlers"+filterList_c;h.className="controlers-filters";h.dataset.filterType=l[b].filter;document.getElementById("controlersPanel").appendChild(h);if("csvfilter"==l[b].filter){m=[];l=data.getDistinctValues(c).toString().split(",");
for(n in l)""!=l[n].trim()&&m.push(l[n].trim());m=m.filter(function(a,b,c){return 0>c.indexOf(a,b+1)})}l=prefs.getString("categoryCaption");h=d;b="vertical";"insidefilter"==l.toLowerCase()&&(l=h,h="",b="horizontal");d={controlType:"CategoryFilter",containerId:"controlers"+filterList_c,options:{filterColumnIndex:c,filterColumnLabel:d,values:m,ui:{label:h,caption:l,allowTyping:!1,allowMultiple:!0,selectedValuesLayout:"belowWrapping",labelStacking:b}}};g in filterSettings&&(d.state={selectedValues:filterSettings[g]});
null!=m&&(d.dataTable=data);g=new google.visualization.ControlWrapper(d);null!=m?csvFilters.push([g,c]):filterList.push([g,c]);filterList_c++;break}}0==filterList.length&&0!=csvFilters.length&&(h=document.createElement("div"),h.id="controlers"+filterList_c,h.style.display="none",h.dataset.filterType="stringfilter",document.getElementById("controlersPanel").appendChild(h),l=prefs.getString("categoryCaption"),b="vertical","insidefilter"==l.toLowerCase()&&(b="horizontal"),d={controlType:"StringFilter",
containerId:"controlers"+filterList_c,options:{filterColumnIndex:0,filterColumnLabel:"csvFilterOnly",useFormattedValue:!0,matchType:"any",ui:{label:"csvFilterOnly",labelStacking:b}}},g=new google.visualization.ControlWrapper(d),filterList.push([g,c]),filterList_c++);"MarkerClusterer"!=visualizationType||"lat"in mapsParam.column||"lng"in mapsParam.column||!("address"in mapsParam.column||2>=columnsToDisplay.length)?"lat"in mapsParam.column&&"lng"in mapsParam.column||(mapsParam.column={lat:0,lng:1},
"tooltip"in mapsParam.column||(mapsParam.column.tooltip=2)):(mapsParam.column.lat=data.addColumn("number","latitude"),mapsParam.column.lng=data.addColumn("number","longitude"),"address"in mapsParam.column||(mapsParam.column.address=0),1==columnsToDisplay.length&&(mapsParam.column.tooltip=mapsParam.column.address),"tooltip"in mapsParam.column||(mapsParam.column.tooltip=1),0!=data.getNumberOfRows()&&(mapsParam.geocoder.run=!0))}}
function drawVisualization(a){var f=visualizationType;clearInterval(loader);var e=document.getElementById("loader");e.style.width="100%";"BI"!=visualizationType?setTimeout(function(){e.style.display="none"},500):(e.style.boxShadow="none",e.style.backgroundColor="transparent",e.style.color="#db4437",e.style.fontSize="10pt",e.innerHTML="Building dashboard...");document.body.style.backgroundColor=prefs.getString("backgroundColor");a.getNumberOfColumns();var b=a.getNumberOfRows()-1;if(0>b)f=decodeURI(prefs.getString("errorMSG")),
""==f?document.getElementById("dashboard").innerHTML='<div style="text-align:center; width:100%">No data to display.</div>':document.getElementById("dashboard").innerHTML='<div style="text-align:center; width:100%">'+f+"</div>";else{1==useMapView&&(document.getElementById(mapsParam.divID).style.display="",void 0!=prefs.getString("mapHeight")&&null!=prefs.getString("mapHeight")&&""!=prefs.getString("mapHeight")?document.getElementById(mapsParam.divID).style.height=prefs.getString("mapHeight"):document.getElementById(mapsParam.divID).style.height=
"500px",1==mapsParam.ISmapsLoaded?mapsMarkerClustererFirstLoad():mapsParam.MustReload=!0);if("Table"==visualizationType&&1==columnsLayout){var c=parseInt(prefs.getString("pageSize"));void 0!=q&&(selectedRow=a.getFilteredRows([{column:idColumnPosition,value:q}]),0<selectedRow.length&&(startPage=parseInt(selectedRow[0]/c)));wrapper=new google.visualization.ChartWrapper({chartType:"Table",containerId:"chart1",options:{allowHtml:!0,page:"enable",pageSize:c,startPage:startPage,width:"100%"},view:{columns:columnsToDisplay}});
useMapView&&google.visualization.events.addListener(wrapper,"select",function(a){if(void 0==q||void 0==idColumnPosition){a=wrapper.getChart().getSelection()[0];if(void 0==a||!("row"in a))return;a=a.row;null!=view&&(a=view.rows[a]);if(0==doNotShowMarker){a=mapsParam.markers[a];var b=new google.maps.LatLngBounds(a.position,a.position),c=b.getCenter();b.extend(new google.maps.LatLng(c.lat()+.1,c.lng()+.1));b.extend(new google.maps.LatLng(c.lat()-.1,c.lng()-.1));mapsParam.map.fitBounds(b);google.maps.event.trigger(a,
"click")}}doNotShowMarker=!1});google.visualization.events.addListener(wrapper,"ready",function(a){google.visualization.events.addListener(wrapper.getChart(),"page",function(a){refresh(a.page)});google.visualization.events.addListener(wrapper.getChart(),"sort",function(){refresh("sort")});0==filterList_c&&refresh()})}else if("Table"==visualizationType&&1<columnsLayout){f="Cards";document.getElementById("visualizations").className="viewCards";c=parseInt(prefs.getString("pageSize"));wrapper=new google.visualization.ChartWrapper({chartType:"Table",
containerId:"hidden_chart",options:{page:"enable",pageSize:c},view:{columns:columnsToDisplay}});google.visualization.events.addListener(wrapper,"ready",function(a){google.visualization.events.addListener(wrapper.getChart(),"page",function(a){refresh(a.page)})});for(var g=[],d=0;d<columnsLayout;d++)g.push([]);for(var l=0,d=0;d<b&&(g[l].push(d),l++,l==columnsLayout&&(l=0),d!=c-1);d++);for(d=0;d<columnsLayout;d++)b=document.createElement("div"),b.style.width=Math.floor(100/columnsLayout)+"%",b.style.cssFloat=
"left",c=document.createElement("div"),c.id="tableChart"+d,b.appendChild(c),document.getElementById("chart1").appendChild(b),b=new google.visualization.ChartWrapper({chartType:"Table",containerId:"tableChart"+d,dataTable:a,options:{allowHtml:!0,alternatingRowStyle:!1},view:{rows:g[d],columns:columnsToDisplay}}),b.draw(),subTables.push(b)}else if("Geochart"==visualizationType){5==columnsToDisplay.length?(a.setColumnProperty(columnsToDisplay[4],"html",!0),a.setColumnProperty(columnsToDisplay[4],"role",
"tooltip"),g=2):(a.setColumnProperty(columnsToDisplay[3],"html",!0),a.setColumnProperty(columnsToDisplay[3],"role","tooltip"),g=1);b=a.getDistinctValues(columnsToDisplay[g]);c=[];for(d=0;d<b.length;d++)c.push(d);for(var m=a.addColumn("number"),d=0;d<a.getNumberOfRows();d++)a.setValue(d,m,b.indexOf(a.getValue(d,columnsToDisplay[g])));columnsToDisplay[g]=m;wrapper=new google.visualization.ChartWrapper({chartType:"google.visualization.GeoChart",containerId:"chart1",options:{legend:"none",region:prefs.getString("mapRegion"),
enableRegionInteractivity:!0,colorAxis:{colors:b,values:c},tooltip:{isHtml:!0}},view:{columns:columnsToDisplay}});google.visualization.events.addOneTimeListener(wrapper,"ready",function(a){google.visualization.events.addListener(wrapper.getChart(),"regionClick",function(a){wrapper.setOption("region",a.region);wrapper.draw();document.getElementById("pagination").innerHTML="<img style=\"cursor:pointer\" onclick=\"wrapper.setOption('region', '"+prefs.getString("mapRegion")+"');wrapper.draw();document.getElementById('pagination').innerHTML=''\" src=\"https://lh5.googleusercontent.com/-kqWjLbPl-9o/UwzyksLIe2I/AAAAAAAAH4Y/gfdhODqPQUU/zoom_out.png\">"})});
void 0!=prefs.getString("mapHeight")&&null!=prefs.getString("mapHeight")&&""!=prefs.getString("mapHeight")&&(document.getElementById("chart1").style.height=prefs.getString("mapHeight"))}else"Gantt"==visualizationType?(ganttHeight=initialHeight-150,200>ganttHeight&&(ganttHeight=800),wrapper=new google.visualization.ChartWrapper({chartType:"Timeline",containerId:"chart1",options:{height:ganttHeight,timeline:{colorByRowLabel:!0,groupByRowLabel:!1}},view:{columns:columnsToDisplay}})):"MarkerClusterer"==
visualizationType?(void 0!=prefs.getString("mapHeight")&&null!=prefs.getString("mapHeight")&&""!=prefs.getString("mapHeight")?document.getElementById(mapsParam.divID).style.height=prefs.getString("mapHeight"):document.getElementById(mapsParam.divID).style.height="500px",1==mapsParam.ISmapsLoaded?mapsMarkerClustererFirstLoad():mapsParam.MustReload=!0,wrapper=new google.visualization.ChartWrapper({chartType:"Table",containerId:"hidden_chart",options:{page:"enable",pageSize:1,startPage:1},view:{columns:columnsToDisplay}})):
"BI"==visualizationType&&(document.getElementById("parentChart1").style.width="49%",document.getElementById("sidebar").style.width="49%",document.getElementById("sidebar").style.marginLeft="2%",wrapper=new google.visualization.ChartWrapper({chartType:"Table",containerId:"hidden_chart",options:{page:"enable",pageSize:1,startPage:1},view:{columns:columnsToDisplay}}));if(void 0!=sidebar||""!=sidebarColumn)f="Table + Sidebar",void 0!=sidebar?google.visualization.events.addListener(wrapper,"select",function(b){if(void 0!=
q&&void 0!=idColumnPosition){var c=void 0;b=a.getNumberOfRows()-1;for(var d=0;d<b;d++)if(a.getValue(d,idColumnPosition)==q){c=d;break}1!=useMapView&&(q=void 0);if(void 0==c)return;b=a.getValue(c,sidebar)}else{b=wrapper.getChart().getSelection()[0];if(void 0==b||!("row"in b))return;c=b.row;null!=view&&(c=view.rows[c]);b=wrapper.getDataTable().getValue(c,sidebar);if(useMapView&&0==doNotShowMarker&&(c=mapsParam.markers[c],void 0!=c)){var d=new google.maps.LatLngBounds(c.position,c.position),e=d.getCenter();
d.extend(new google.maps.LatLng(e.lat()+.1,e.lng()+.1));d.extend(new google.maps.LatLng(e.lat()-.1,e.lng()-.1));mapsParam.map.fitBounds(d);google.maps.event.trigger(c,"click")}}doNotShowMarker=!1;document.getElementById("sidebar").innerHTML=b;delete b;adjustHeight()}):google.visualization.events.addListener(wrapper,"select",function(a){a=wrapper.getChart().getSelection()[0].row;null!=view&&(a=view.rows[a]);a=wrapper.getDataTable().getValue(a,0);var b=new google.visualization.Query(queryString);b.setQuery("Select "+
sidebarColumn+" where "+idColumn+' = "'+a+'"');document.getElementById("sidebar").innerHTML='<div id="loaderForSidebar" class="loader"></div>';l=10;loader=setInterval(function(){document.getElementById("loaderForSidebar").style.width=l+"%";l+=10;90<l&&clearInterval(loader)},1E3);b.send(handleQueryResponseForSidebarData)}),document.getElementById("parentChart1").style.width="40%",document.getElementById("sidebar").style.width="59%",document.getElementById("sidebar").style.marginLeft="1%";if(0<filterList_c&&
0!=filterList.length){g=new google.visualization.Dashboard(document.getElementById("dashboard"));for(d=0;d<filterList.length;d++)g.bind(filterList[d][0],wrapper);for(d=0;d<csvFilters.length;d++)google.visualization.events.addListener(csvFilters[d][0],"statechange",function(){refresh("customCategoryFilter")}),csvFilters[d][0].draw();for(d=0;d<dependentFilterList.length;d++)for(c=b=!1,m=filterList.concat(csvFilters),j=0;j<m.length;j++)m[j][1]==dependentFilterList[d][0]&&(b=m[j][0]),m[j][1]==dependentFilterList[d][1]&&
(c=m[j][0]),b&&c&&g.bind(b,c);google.visualization.events.addListener(g,"ready",function(){void 0!=q&&0<selectedRow.length&&wrapper.getChart().setSelection([{row:selectedRow[0]}]);refresh("ready")});google.visualization.events.addOneTimeListener(g,"ready",function(){actionsToExecuteOnlyOnFirstReady()});g.draw(a)}else if(0==filterList_c||0==filterList.length)wrapper.setDataTable(a),google.visualization.events.addListener(wrapper,"ready",function(){void 0!=q&&0<selectedRow.length&&wrapper.getChart().setSelection([{row:selectedRow[0]}]);
refresh("ready")}),google.visualization.events.addOneTimeListener(wrapper,"ready",function(){actionsToExecuteOnlyOnFirstReady()}),wrapper.draw();prefs.getBool("download")&&(document.getElementById("export").style.display="inline");AWTCategorie=f.replace("MarkerClusterer","Maps");1==useMapView&&(AWTCategorie+=" + Maps");AWTAction="";""!=ISAppsScriptProxyUsed&&(AWTAction=""!=AWTAction?AWTAction+" + Proxy":"Proxy");prefs.getString("rangeTemplate")&&(AWTAction=""!=AWTAction?AWTAction+" + Template":"Template");
void 0!=q&&(AWTAction=""!=AWTAction?AWTAction+" + DirectRowLink":"DirectRowLink");0!=Object.keys(filterSettings).length&&(AWTAction=""!=AWTAction?AWTAction+" + PreSetFilters":"PreSetFilters");1==prefs.getBool("download")&&(AWTAction=""!=AWTAction?AWTAction+" + Download":"Download");-1!=customCSS.indexOf("http")&&-1==customCSS.indexOf("/site/scriptsexamples/awesome_table_multipleColumnsLayout.css")&&(AWTAction=""!=AWTAction?AWTAction+" + CustomCSS":"CustomCSS");"settings"in window&&(AWTAction=""!=
AWTAction?AWTAction+" + FireBase":"FireBase");""==AWTAction&&(AWTAction="Default");ga("awesomeTableTracking.send","event",AWTCategorie,AWTAction,document.referrer.split("?")[0]);ga("gadgetTracking.send","event","Awesome Table","Loaded as "+f.replace("MarkerClusterer","Maps")+ISAppsScriptProxyUsed,document.referrer.split("?")[0])}}
function handleQueryResponseForSidebarData(a){a.isError()?document.getElementById("sidebar").innerHTML="Error in query: "+a.getMessage()+" "+a.getDetailedMessage():(a=a.getDataTable().getValue(0,0),document.getElementById("sidebar").innerHTML=a,clearInterval(loader),document.getElementById("loaderForSidebar").style.width="100%",setTimeout(function(){document.getElementById("loaderForSidebar").style.display="none"},500),gadgets.window.adjustHeight())}
function jumpTo(a,f){q=a;idColumn=f;for(var e=data.getNumberOfColumns(),b=0;b<e;b++)if(data.getColumnId(b)==idColumn){idColumnPosition=b;break}void 0!=q&&void 0!=idColumnPosition&&google.visualization.events.trigger(wrapper,"select",{})}
function toggleDisplay(a,f,e){var b=a.parentNode;for(a=0;10>a&&"DIV"!=b.tagName;a++)b=b.parentNode;var c=b.getElementsByClassName(f)[0];""==c.innerHTML&&(c.innerHTML=e);e=b.getElementsByClassName("show");for(a=0;a<e.length;a++)0==e[a].classList.contains(f)&&(e[a].classList.toggle("hide"),e[a].classList.toggle("show"),a--);c.classList.toggle("hide");c.classList.toggle("show");adjustHeight()}
function refresh(a){if("getChart"in wrapper){var f=wrapper.getChart();if("getSortInfo"in f)var e=f.getSortInfo()}var b=wrapper.getDataTable();if(void 0!=wrapper.getView().rows)f=wrapper.getView().rows.length,wrapper.setView({columns:columnsToDisplay});else if(f=b.getNumberOfRows(),0<csvFilters.length&&"customCategoryFilter"!=a)for(var c=0;c<csvFilters.length;c++)if(0<csvFilters[c][0].getState().selectedValues.length){var g=!0;break}if("customCategoryFilter"==a||g){useRowsToDisplay=!0;rowsToDisplay=
[];g=!0;f=b.getNumberOfRows();for(c=0;c<f;c++){for(var d=!0,l=0;l<csvFilters.length;l++){var m=csvFilters[l][0].getState().selectedValues;if(0<m.length){var g=!1,h=b.getValue(c,csvFilters[l][1]);null==h&&(h="");h=h.split(",").map(function(a){return a.trim()});for(k in m)-1==h.indexOf(m[k])&&(d=!1)}}d&&rowsToDisplay.push(c)}g?(view=null,wrapper.setView({columns:columnsToDisplay}),rowsToDisplay=[],useRowsToDisplay=!1):(view={rows:rowsToDisplay,columns:columnsToDisplay},isNaN(a)?wrapper.setOption("startPage",
0):(wrapper.setOption("startPage",a),startPage=a),wrapper.setView({rows:rowsToDisplay,columns:columnsToDisplay}));google.visualization.events.removeAllListeners(wrapper.getChart());void 0!=e&&(wrapper.setOption("sortColumn",e.column),wrapper.setOption("sortAscending",e.ascending));wrapper.draw()}else{g=document.getElementsByClassName("charts-menu-button-dropdown");for(c=0;c<g.length;c++)g[c].innerHTML="\u25bc";g=1;l=f;if("Table"==visualizationType){h=parseInt(prefs.getString("pageSize"));0!=startPage&&
(a=startPage);isNaN(a)?("sort"!=a&&0==f&&(g=0),l=f>h?h:f):(d=a,g=d*h+1,l=f>(d+1)*h?(d+1)*h:f);0<startPage&&(g=startPage*h+1,l=f>(startPage+1)*h?(startPage+1)*h:f,startPage=0);var d=Math.round(g/h),m=document.getElementById("pagination"),p=document.getElementById("paginationBottom");p.innerHTML="";var n=document.getElementsByClassName("google-visualization-table-div-page");1<n.length?(n=document.getElementsByClassName("google-visualization-table-div-page"),m.innerHTML="",m.appendChild(n[0]),p.appendChild(attachEvents(n[0].cloneNode(!0),
d))):1==n.length&&0==m.getElementsByClassName("google-visualization-table-div-page").length?(m.innerHTML="",m.appendChild(n[0]),p.appendChild(attachEvents(n[0].cloneNode(!0),d))):0<n.length&&1==n[0].childNodes.length?m.innerHTML="":""!=m.innerHTML&&p.appendChild(attachEvents(m.childNodes[0].cloneNode(!0),d));if(1<columnsLayout){d=[];for(c=0;c<columnsLayout;c++)d.push([]);p=m=0;isNaN(a)?0!=startPage&&(p=startPage*h):p=a*h;a=null==view?!0:!1;for(c=p;c<f&&(a?d[m].push(c):d[m].push(view.rows[c]),m++,
m==columnsLayout&&(m=0),c!=p+h-1);c++);for(c=0;c<d.length;c++)subTables[c].setDataTable(b),subTables[c].setView({rows:d[c],columns:columnsToDisplay}),subTables[c].draw()}}else"BI"==visualizationType?setTimeout(function(){for(var a in bi_charts)bi_charts[a].getChart().clearChart();bi_charts=[];document.getElementById("chart1").innerHTML="";document.getElementById("sidebar").innerHTML="";UPDATE_BI_VIEW(b,0)},50):"MarkerClusterer"==visualizationType&&0==mapsParam.geocoder.run?setTimeout(function(){UPDATE_MAP_MARKERCLUSTERER(b)},
50):"Gantt"==visualizationType&&(a=document.getElementById("chart1"),null!=a&&(h=a.getElementsByTagName("svg"),null!=h&&"length"in h&&1==h.length?(h=h[0],d=h.getBBox().height,h.parentElement.parentElement.style.height=d,h.style.height=d,delete h):null!=h&&"length"in h&&2==h.length&&(h=h[0],ganttHeight=initialHeight-150,200>ganttHeight&&(ganttHeight=800),h.parentElement.parentElement.style.height=ganttHeight),delete a));1==useMapView&&setTimeout(function(){UPDATE_MAP_MARKERCLUSTERER(b)},50);a=document.getElementsByClassName("numberOfResultsShown");
for(c in a)a[c].innerHTML="<b>"+g+"</b> - <b>"+l+"</b> / <b>"+f+"</b>";""!=sidebarColumn&&0==selectedRow.length?document.getElementById("sidebar").innerHTML='<p style="margin-top:10%;color:grey">\u2190<br>\u2190<br>\u2190</p>':selectedRow=[];"BI"!=visualizationType&&adjustHeight();if(prefs.getBool("download")){d='"';m=JSON.parse(b.toJSON()).rows;null!=view&&(m=view.rows);for(c=0;c<columnsToDisplay.length;c++)d+=data.getColumnLabel(columnsToDisplay[c]).toString().replace(/"/g,'""'),c<columnsToDisplay.length-
1&&(d+='","');d+='"\r\n';a=0>=f-m[m.length-1]&&null==view?!0:!1;for(c=0;c<m.length;c++){d+='"';for(l=0;l<columnsToDisplay.length;l++)h=a?b.getValue(c,columnsToDisplay[l]):b.getValue(m[c],columnsToDisplay[l]),null!=h&&(d+=h.toString().replace(/"/g,'""')),l<columnsToDisplay.length-1&&(d+='","');d+='"\r\n'}c="data:text/csv;charset=utf-8,"+encodeURIComponent(d);a=document.getElementById("export");a.href=c;a.download="export.csv"}setupVisibilityToggle();void 0!=wrapper&&void 0!=wrapper.getChart()&&0<f?
(void 0!=e&&(wrapper.setOption("sortColumn",e.column),wrapper.setOption("sortAscending",e.ascending)),void 0!=q&&void 0!=idColumnPosition?google.visualization.events.trigger(wrapper,"select",{}):void 0!=sidebar&&""!=sidebar&&(e=wrapper.getChart().getSortInfo().sortedIndexes,wrapper.getChart().setSelection([{row:null!=e?e[g-1]:g-1}]),doNotShowMarker=!0,google.visualization.events.trigger(wrapper,"select",{}))):document.getElementById("sidebar").innerHTML="";gadgets.window.adjustHeight()}}
function UPDATE_BI_VIEW(a,f){if(f>=columnsToDisplay.length)setTimeout(function(){document.getElementById("loader").style.display="none";setupVisibilityToggle();gadgets.window.adjustHeight()},500);else{for(var e=0;e<filterList.length;e++)filterList[e][1]==f&&(document.getElementById("loader").style.display="inline");document.getElementById("loader").innerHTML="Creating chart "+(f+1)+"/"+columnsToDisplay.length+"...";var e=columnsToDisplay[f],b=document.getElementById("chart1"),c=document.getElementById("sidebar"),
g=document.createElement("div");g.id="BIchart"+e;f%2?c.appendChild(g):b.appendChild(g);b=a.getColumnType(e);if("string"==b){b=google.visualization.data.group(a,[e],[{column:e,aggregation:google.visualization.data.count,type:"number"}]);c=0;if(""==b.getValue(0,0)||null==b.getValue(0,0))c=b.getValue(0,1),b.removeRow(0);if(1==b.getNumberOfRows()){g.style.padding="10px";b.setColumnLabel(1,"Nb of results");var d=new google.visualization.ChartWrapper({chartType:"Table",containerId:"BIchart"+e,dataTable:b});
google.visualization.events.addOneTimeListener(d,"ready",function(){setTimeout(function(){UPDATE_BI_VIEW(a,f+1)},50)});setTimeout(function(){d.draw()},50);bi_charts.push(d)}else if(7>b.getNumberOfRows())g.style.height=document.body.clientWidth/2*60/100,d=new google.visualization.ChartWrapper({chartType:"PieChart",containerId:"BIchart"+e,dataTable:b,options:{title:a.getColumnLabel(e),titleTextStyle:{fontSize:14},chartArea:{width:"100%"},legend:{position:"labeled"}}}),google.visualization.events.addOneTimeListener(d,
"ready",function(){setTimeout(function(){UPDATE_BI_VIEW(a,f+1)},50)}),setTimeout(function(){d.draw()},50),bi_charts.push(d);else if(b.getNumberOfRows()<=(a.getNumberOfRows()-c)/2)g.style.padding="10px",b.setColumnLabel(1,"Top results"),b.sort([{column:1,desc:!0}]),d=new google.visualization.ChartWrapper({chartType:"Table",containerId:"BIchart"+e,dataTable:b}),15<b.getNumberOfRows()&&d.setView({rows:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]}),google.visualization.events.addOneTimeListener(d,"ready",function(){setTimeout(function(){UPDATE_BI_VIEW(a,
f+1)},50)}),setTimeout(function(){d.draw()},50),bi_charts.push(d);else{c="";b=new google.visualization.DataTable;b.addColumn("string",a.getColumnLabel(e));for(j=0;j<a.getNumberOfRows();j++){var l=a.getValue(j,e);""!=l&&(c+=l+" ",b.addRow([l]))}var m={},h={"null":1,"":1,a:1,o:1,e:1,es:1,em:1,eu:1,able:1,about:1,across:1,after:1,all:1,almost:1,also:1,am:1,among:1,an:1,and:1,any:1,are:1,as:1,at:1,be:1,because:1,been:1,but:1,by:1,can:1,cannot:1,could:1,dear:1,did:1,"do":1,does:1,either:1,"else":1,ever:1,
every:1,"for":1,from:1,get:1,got:1,had:1,has:1,have:1,he:1,her:1,hers:1,him:1,his:1,how:1,however:1,i:1,"if":1,"in":1,into:1,is:1,it:1,its:1,just:1,least:1,let:1,like:1,likely:1,may:1,me:1,might:1,most:1,must:1,my:1,neither:1,no:1,nor:1,not:1,of:1,off:1,often:1,on:1,only:1,or:1,other:1,our:1,own:1,rather:1,said:1,say:1,says:1,she:1,should:1,since:1,so:1,some:1,than:1,that:1,the:1,their:1,them:1,then:1,there:1,these:1,they:1,"this":1,tis:1,to:1,too:1,twas:1,us:1,wants:1,was:1,we:1,were:1,what:1,when:1,
where:1,which:1,"while":1,who:1,whom:1,why:1,will:1,"with":1,would:1,yet:1,you:1,your:1,le:1,la:1,des:1,les:1,est:1,sont:1,non:1,sauf:1,de:1,un:1,"\u00eatre":1,et:1,"\u00e0":1,il:1,avoir:1,ne:1,je:1,son:1,que:1,se:1,qui:1,ce:1,dans:1,en:1,du:1,elle:1,au:1,de:1,ce:1,le:1,pour:1,pas:1,que:1,vous:1,par:1,sur:1,faire:1,plus:1,dire:1,me:1,on:1,mon:1,lui:1,nous:1,comme:1,mais:1,pouvoir:1,avec:1,tout:1,y:1,aller:1,voir:1,en:1,bien:1,"o\u00f9":1,sans:1,tu:1,ou:1,leur:1,homme:1,si:1,deux:1,mari:1,moi:1,vouloir:1,
te:1,femme:1,venir:1,quand:1,grand:1,celui:1,si:1,notre:1,devoir:1,"l\u00e0":1,jour:1,prendre:1,"m\u00eame":1,votre:1,tout:1,rien:1,petit:1,encore:1,aussi:1,quelque:1,dont:1,tout:1,mer:1,trouver:1,donner:1,temps:1,"\u00e7a":1,peu:1,"m\u00eame":1,falloir:1,sous:1,parler:1,alors:1,main:1,chose:1,ton:1,mettre:1,vie:1,savoir:1,yeux:1,passer:1};c.split(" ").map(function(a){a=a.toLowerCase();/\W|\d/.test(a)||h[a]||(null==m[a]&&(m[a]=0),m[a]++)});for(var c=Object.keys(m).slice(0).sort(function(a,b){return m[b]-
m[a]}).slice(0,50),l=m[c[0]],p=m[c[c.length-1]],n=shuffle_(c),c="<b>"+a.getColumnLabel(e)+' - Top words</b><div style="text-align: center">',u=0,v="#415994 #416D62 #B43C39 #D5C252 #DEAE52 #BD5531 #5A8141".split(" "),r=0;r<n.length;r++)c+='<span title="'+m[n[r]]+'" style="font-size:'+Math.round(28*(m[n[r]]-p)/(l-p)+12)+"px;font-weight:bold;color:"+v[Math.floor(Math.random()*v.length)]+'">'+n[r].toUpperCase()+" </span>",u++,6==u&&(c+="<br>",u=0);g.innerHTML="<div>"+(c+"</div>")+'<div data-toggle-visibility="controller" data-view="bi" style="cursor:pointer;padding:5px;background-color:#F4F4F4;text-align:center;font-weight:bold;font-size:14px;color:#444;margin:0px 30px;">Details <span style="color:#9F9F9F;font-size:10px">\u25bc</span></div><div data-toggle-visibility="target"><div id="details_'+
e+'" style="margin:0px 30px;height:300px;overflow:scroll"></div></div></div>';(new google.visualization.Table(document.getElementById("details_"+e))).draw(b,{sortColumn:0,sortAscending:!1,page:"enable",pageSize:10,startPage:1});setTimeout(function(){UPDATE_BI_VIEW(a,f+1)},50)}}else"number"==b?(b=google.visualization.data.group(a,[e],[{column:e,aggregation:google.visualization.data.count,type:"number"}]),3>b.getNumberOfRows()?(b.setColumnLabel(1,"Nb of results"),d=new google.visualization.ChartWrapper({chartType:"Table",
containerId:"BIchart"+e,dataTable:b})):13>b.getNumberOfRows()?(""==b.getValue(0,0)&&b.removeRow(0),g=google.visualization.data.group(a,[{column:0,type:"number",modifier:function(){return 1}}],[{column:e,type:"number",aggregation:google.visualization.data.avg}]),d=new google.visualization.ChartWrapper({chartType:"ColumnChart",containerId:"BIchart"+e,dataTable:b,options:{title:a.getColumnLabel(e)+" - on average: "+g.getValue(0,1).toFixed(2),titleTextStyle:{fontSize:14},legend:{position:"none"}}})):
(g=google.visualization.data.group(a,[{column:0,type:"number",modifier:function(){return 1}}],[{column:e,type:"number",aggregation:google.visualization.data.sum}]),d=new google.visualization.ChartWrapper({chartType:"Table",containerId:"BIchart"+e,dataTable:g,view:{columns:[1]}})),google.visualization.events.addOneTimeListener(d,"ready",function(){setTimeout(function(){UPDATE_BI_VIEW(a,f+1)},50)}),setTimeout(function(){d.draw()},50),bi_charts.push(d)):"date"==b||"datetime"==b?(b="date"==b?google.visualization.data.group(a,
[e],[{column:e,aggregation:google.visualization.data.count,type:"number"}]):google.visualization.data.group(a,[{column:e,modifier:function(a){if(null!=a)return new Date(a.getFullYear(),a.getMonth(),a.getDate())},type:"date"}],[{column:e,aggregation:google.visualization.data.count,type:"number"}]),d=new google.visualization.ChartWrapper({chartType:"LineChart",containerId:"BIchart"+e,dataTable:b,options:{title:a.getColumnLabel(e),titleTextStyle:{fontSize:14},legend:{position:"none"}}}),google.visualization.events.addOneTimeListener(d,
"ready",function(){setTimeout(function(){UPDATE_BI_VIEW(a,f+1)},50)}),setTimeout(function(){d.draw()},50),bi_charts.push(d)):setTimeout(function(){UPDATE_BI_VIEW(a,f+1)},50)}}
function UPDATE_MAP_MARKERCLUSTERER(a){if(!mapsParam.ISinsideUpdate){mapsParam.ISinsideUpdate=!0;if(useRowsToDisplay)var f=rowsToDisplay.length,e=function(a){return rowsToDisplay[a]};else f=a.getNumberOfRows(),e=function(a){return a};mapsParam.markers.forEach(function(a,b){a.setMap(null)});mapsParam.markers=[];mapsParam.mc.clearMarkers();if(!(1>f)){var b=new google.maps.LatLng(a.getValue(e(0),mapsParam.column.lat),a.getValue(e(0),mapsParam.column.lng));if(!isNaN(b.lat())&&!isNaN(b.lng())){for(var c=
void 0,g=0;g<f;g++)if(null!=a.getValue(e(g),mapsParam.column.lat)&&null!=a.getValue(e(g),mapsParam.column.lng)){b=new google.maps.LatLng(a.getValue(e(g),mapsParam.column.lat),a.getValue(e(g),mapsParam.column.lng));void 0==c?c=new google.maps.LatLngBounds(b,b):c.extend(b);var d="tooltip"in mapsParam.column?a.getValue(e(g),mapsParam.column.tooltip):"",l=new google.maps.Marker({position:b,title:""});l.toolTip=d;attachMarkerInfoWindows(l,d);if(void 0!=q&&void 0!=idColumnPosition&&a.getValue(e(g),idColumnPosition)==
q)var m=l;l.indexView=g;mapsParam.markers.push(l)}try{mapsParam.mc.clearMarkers();mapsParam.mc.addMarkers(mapsParam.markers);void 0!=m&&(c=new google.maps.LatLngBounds(m.position,m.position));if(c.getNorthEast().equals(c.getSouthWest())){var h=c.getCenter();c.extend(new google.maps.LatLng(h.lat()+.1,h.lng()+.1));c.extend(new google.maps.LatLng(h.lat()-.1,h.lng()-.1))}mapsParam.map.fitBounds(c)}catch(p){}1==f?google.maps.event.trigger(l,"click"):void 0!=m&&(google.maps.event.trigger(m,"click"),q=void 0)}}mapsParam.ISinsideUpdate=
!1}}function attachMarkerInfoWindows(a,f){""!=f&&google.maps.event.addListener(a,"click",function(){null!=mapsParam.InfoWindow.getMap()&&mapsParam.InfoWindow.close();mapsParam.InfoWindow.setContent(f);mapsParam.InfoWindow.open(a.get("map"),a)})}function shuffle_(a){var f,e,b=a.length;if(b)for(;--b;)e=Math.floor(Math.random()*(b+1)),f=a[e],a[e]=a[b],a[b]=f;return a}
function attachEvents(a,f){var e=wrapper.getChart().getSortInfo();sortColumn=e.column;sortAscending=e.ascending;e=a.childNodes;for(i in e)void 0!=e[i].className&&-1!=e[i].className.indexOf("left")&&-1==e[i].className.indexOf("disabled")?e[i].onclick=function(){google.visualization.events.removeAllListeners(wrapper.getChart());wrapper.setOption("startPage",f+1);wrapper.setOption("sortColumn",sortColumn);wrapper.setOption("sortAscending",sortAscending);wrapper.draw();refresh(f+1)}:void 0!=e[i].className&&
-1!=e[i].className.indexOf("right")&&-1==e[i].className.indexOf("disabled")&&(e[i].onclick=function(){google.visualization.events.removeAllListeners(wrapper.getChart());wrapper.setOption("startPage",f-1);wrapper.setOption("sortColumn",sortColumn);wrapper.setOption("sortAscending",sortAscending);wrapper.draw();refresh(f-1)});return a}
function setupVisibilityToggle(){for(var a=document.querySelectorAll('[data-toggle-visibility="controller"]'),f=0;f<a.length;f++)a[f].onclick="bi"==a[f].dataset.view?function(){var a=this.parentNode.querySelector('[data-toggle-visibility="target"]');a.classList.toggle("show");a.classList.toggle("hide")}:function(){var a=this.parentNode.querySelector('[data-toggle-visibility="target"]');a.classList.toggle("show");a.classList.toggle("hide");adjustHeight()};a=document.querySelectorAll('[data-toggle-visibility="target"]');
for(f=0;f<a.length;f++)a[f].classList.add("hide")}
function actionsToExecuteOnlyOnFirstReady(){if("insidefilter"==prefs.getString("categoryCaption").toLowerCase())for(var a=document.getElementsByClassName("google-visualization-controls-stringfilter"),f=0;f<a.length;f++){var e=a[f].getElementsByTagName("label")[0];a[f].getElementsByTagName("input")[0].placeholder=e.innerHTML;e.parentNode.removeChild(e)}else document.getElementById("controlersPanel").className+=" NOinsideFilter";var b=document.getElementsByClassName("google-visualization-table-tr-sel");0<
b.length&&null!=b[0].querySelector('[data-toggle-visibility="target"]')&&(f=b[0].querySelector('[data-toggle-visibility="target"]').classList,f.remove("hide"),f.add("show"),setTimeout(function(){b[0].scrollIntoView(!0)},500));for(f=0;f<filterList.length;f++)if("DateRangeFilter"==filterList[f][0].getControlType()){var e=filterList[f][0],c=document.getElementById(e.getContainerId()),a=c.parentNode;if("daterangefilter"==c.dataset.filterType)for(var c=e.getState(),e=c.lowValue.toJSON(),e=e.substring(0,
e.indexOf("T")),c=c.highValue.toJSON(),c=c.substring(0,c.indexOf("T")),a=a.getElementsByTagName("input"),g=0;g<a.length;g++){var d=a[g];if("low"==d.dataset.rangeExtent||"high"==d.dataset.rangeExtent)d.min=e,d.max=c,d.value="low"==d.dataset.rangeExtent?e:c,d.onchange=function(){var a=this.parentNode.dataset.filterIndex,b=filterList[a][0].getState();"low"==d.dataset.rangeExtent?b.lowValue=new Date(this.value):b.highValue=new Date(this.value);b.lowThumbAtMinimum=!1;b.highThumbAtMaximum=!1;filterList[a][0].setState(b);
filterList[a][0].draw()}}}}function adjustHeight(){gadgets.window.adjustHeight();window.setTimeout(function(){gadgets.window.adjustHeight()},500);window.setTimeout(function(){gadgets.window.adjustHeight()},1E3);window.setTimeout(function(){gadgets.window.adjustHeight()},2E3);window.setTimeout(function(){gadgets.window.adjustHeight()},5E3)}
if("settings"in window)getData();else{google.setOnLoadCallback(getData);var adjustingHeight={old:0,beforeOld:0};window.onresize=function(){var a=gadgets.window.getHeight();adjustingHeight.beforeOld==a&&adjustingHeight.beforeOld<adjustingHeight.old||(adjustingHeight.beforeOld=adjustingHeight.old,adjustingHeight.old=a,gadgets.window.adjustHeight())}};
